ALTER TABLE users ADD COLUMN phone VARCHAR(40) NULL;

ALTER TABLE users ADD COLUMN location VARCHAR(150) NULL;

ALTER TABLE users ADD COLUMN headline VARCHAR(180) NULL;

ALTER TABLE users ADD COLUMN bio TEXT NULL;

ALTER TABLE users ADD COLUMN linkedin_url VARCHAR(300) NULL;

ALTER TABLE users ADD COLUMN github_url VARCHAR(300) NULL;

ALTER TABLE users ADD COLUMN website_url VARCHAR(300) NULL;

ALTER TABLE users ADD COLUMN cv_url VARCHAR(500) NULL;

ALTER TABLE users ADD COLUMN skills JSON NULL;

ALTER TABLE users ADD COLUMN experience JSON NULL;

ALTER TABLE users ADD COLUMN education JSON NULL;

ALTER TABLE users ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1;